### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by thomotron** [poshcodebear/PoshMailKit#59]
Not an issue, just wanted to thank you for making this :)

`Send-MailMessage` was delightfully simple to use and was quite easy to just plug into scripts for reporting. The fact you've made this a drop-in replacement is fantastic and has saved me (and hopefully others) a bunch of time.

**Comment by poshcodebear** [comment]
Thanks for that! Do let me know here if you find any bugs that worked correctly with Send-MailMessage, or if there are improvements that you'd like to see.
